name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      push_to_registry:
        description: 'Push to registry'
        required: true
        default: true
        type: boolean
      local_testing:
        description: 'Local testing mode (skips registry operations)'
        required: false
        default: false
        type: boolean

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect local testing environment
        id: detect-local
        run: |
          # Detect if running under act or other local testing conditions
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && (-n "$ACT" || -n "$ACT_LOCAL_TESTING" || "${{ runner.name }}" == "Hosted Agent") ]]; then
            echo "local_testing=true" >> $GITHUB_OUTPUT
            echo "push_to_registry=false" >> $GITHUB_OUTPUT
            echo "🔧 Local testing environment detected - disabling registry operations"
          else
            echo "local_testing=${{ inputs.local_testing }}" >> $GITHUB_OUTPUT
            echo "push_to_registry=${{ inputs.push_to_registry }}" >> $GITHUB_OUTPUT
            echo "🚀 Production environment detected - using input parameters"
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Extract version from pyproject.toml
        id: version
        run: |
          VERSION=$(python -c "
          import tomllib
          with open('owasp_zap_mcp/pyproject.toml', 'rb') as f:
              data = tomllib.load(f)
          print(data['project']['version'])
          ")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version extracted: $VERSION"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: ${{ steps.detect-local.outputs.push_to_registry == 'true' && steps.detect-local.outputs.local_testing == 'false' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        if: ${{ steps.detect-local.outputs.local_testing == 'false' || steps.detect-local.outputs.push_to_registry == 'true' }}
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.version.outputs.version }}
            type=raw,value=latest

      - name: Build and push Docker image
        if: ${{ success() }}
        uses: docker/build-push-action@v5
        with:
          context: ./owasp_zap_mcp
          file: ./owasp_zap_mcp/Dockerfile
          platforms: ${{ steps.detect-local.outputs.local_testing == 'true' && 'linux/amd64' || 'linux/amd64,linux/arm64' }}
          push: ${{ steps.detect-local.outputs.push_to_registry == 'true' && steps.detect-local.outputs.local_testing == 'false' }}
          tags: ${{ steps.meta.outputs.tags || format('{0}/{1}:{2}', env.REGISTRY, env.IMAGE_NAME, steps.version.outputs.version) }}
          labels: ${{ steps.meta.outputs.labels || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: ${{ steps.detect-local.outputs.local_testing == 'true' }}

      - name: Output image details
        run: |
          echo "🔍 Build Configuration:"
          echo "  Local Testing: ${{ steps.detect-local.outputs.local_testing }}"
          echo "  Push to Registry: ${{ steps.detect-local.outputs.push_to_registry }}"
          echo "  Environment: ${{ env.ACT && 'act (local)' || 'GitHub Actions' }}"
          echo "  Runner: ${{ runner.name }}"
          echo ""
          echo "📦 Image Details:"
          echo "  Version: ${{ steps.version.outputs.version }}"
          if [[ "${{ steps.detect-local.outputs.local_testing }}" == "true" ]]; then
            echo "  Mode: Local build (image loaded to Docker daemon)"
            echo "  Registry Push: Skipped (local testing mode)"
          else
            echo "  Tags: ${{ steps.meta.outputs.tags }}"
            echo "  Registry Push: ${{ steps.detect-local.outputs.push_to_registry == 'true' && 'Enabled' || 'Disabled' }}"
          fi
